In [3]:
import numpy as np

class MLP:
    def __init__(self, input_size, hidden_sizes, output_size):
        self.layers = []
        self.activations = []
        self.activation_derivatives = []

       
        self.layers.append(np.random.randn(input_size, hidden_sizes[0]) * 0.01)
        self.activations.append(self.tanh)
        self.activation_derivatives.append(self.tanh_derivative)

        
        for i in range(len(hidden_sizes) - 1):
            self.layers.append(np.random.randn(hidden_sizes[i], hidden_sizes[i + 1]) * 0.01)
            self.activations.append(self.relu)
            self.activation_derivatives.append(self.relu_derivative)

        
        self.layers.append(np.random.randn(hidden_sizes[-1], output_size) * 0.01)
        self.activations.append(self.softmax)
       

    def forward(self, X):
        self.z_values = []
        self.a_values = [X]

        
        for i, layer in enumerate(self.layers):
            z = np.dot(self.a_values[-1], layer)
            self.z_values.append(z)
            a = self.activations[i](z)
            self.a_values.append(a)

        return self.a_values[-1]

    

    def train(self, X, y, epochs, learning_rate):
        for epoch in range(epochs):
            self.forward(X)
            

    
    def tanh(self, x):
        return np.tanh(x)

    def tanh_derivative(self, x):
        return 1 - np.tanh(x) ** 2

    def relu(self, x):
        return np.maximum(0, x)

    def relu_derivative(self, x):
        return np.where(x > 0, 1, 0)

    def softmax(self, x):
        e_x = np.exp(x - np.max(x, axis=1, keepdims=True))  
        return e_x / e_x.sum(axis=1, keepdims=True)

    
    def softmax_derivative(self, output):
        
        return output * (1 - output)  

if __name__ == "__main__":
    
    X = np.array([[0.4, 0.5], [0.5, 0.2], [0.5, 0.7], [0.2, 0.7]])
    y = np.array([[0, 1], [0, 1], [1, 0], [1, 0]])  # Binary classification with one-hot encoding

    
    mlp = MLP(input_size=2, hidden_sizes=[3, 3], output_size=5)
    mlp.train(X, y, epochs=1000, learning_rate=0.01)

    
    predictions = mlp.forward(X)
    print("Predictions after training:")
    print(predictions)


Predictions after training:
[[0.2000002  0.19999995 0.19999988 0.19999986 0.20000011]
 [0.20000027 0.19999993 0.19999984 0.19999982 0.20000015]
 [0.20000025 0.19999993 0.19999985 0.19999983 0.20000014]
 [0.20000009 0.19999998 0.19999995 0.19999994 0.20000005]]
